# Generated by Django 3.0.6 on 2020-05-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollnumber', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
